/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClubRouteImport } from './routes/club'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as MeRouteImport } from './routes/me'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ClubIndexRouteImport } from './routes/club.index'
import { Route as ClubAttendanceRouteImport } from './routes/club.attendance'
import { Route as ClubManageRouteImport } from './routes/club.manage'
import { Route as ClubScheduleRouteImport } from './routes/club.schedule'
import { Route as PaymentsTossFailRouteImport } from './routes/payments.toss.fail'
import { Route as PaymentsTossSuccessRouteImport } from './routes/payments.toss.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubAttendanceRoute = ClubAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ClubRoute,
} as any)
const ClubManageRoute = ClubManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ClubRoute,
} as any)
const ClubScheduleRoute = ClubScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ClubRoute,
} as any)
const PaymentsTossFailRoute = PaymentsTossFailRouteImport.update({
  id: '/payments/toss/fail',
  path: '/payments/toss/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsTossSuccessRoute = PaymentsTossSuccessRouteImport.update({
  id: '/payments/toss/success',
  path: '/payments/toss/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRouteWithChildren
  '/games': typeof GamesRoute
  '/lessons': typeof LessonsRoute
  '/me': typeof MeRoute
  '/records': typeof RecordsRoute
  '/club/attendance': typeof ClubAttendanceRoute
  '/club/manage': typeof ClubManageRoute
  '/club/schedule': typeof ClubScheduleRoute
  '/club/': typeof ClubIndexRoute
  '/payments/toss/fail': typeof PaymentsTossFailRoute
  '/payments/toss/success': typeof PaymentsTossSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/games': typeof GamesRoute
  '/lessons': typeof LessonsRoute
  '/me': typeof MeRoute
  '/records': typeof RecordsRoute
  '/club/attendance': typeof ClubAttendanceRoute
  '/club/manage': typeof ClubManageRoute
  '/club/schedule': typeof ClubScheduleRoute
  '/club': typeof ClubIndexRoute
  '/payments/toss/fail': typeof PaymentsTossFailRoute
  '/payments/toss/success': typeof PaymentsTossSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRouteWithChildren
  '/games': typeof GamesRoute
  '/lessons': typeof LessonsRoute
  '/me': typeof MeRoute
  '/records': typeof RecordsRoute
  '/club/attendance': typeof ClubAttendanceRoute
  '/club/manage': typeof ClubManageRoute
  '/club/schedule': typeof ClubScheduleRoute
  '/club/': typeof ClubIndexRoute
  '/payments/toss/fail': typeof PaymentsTossFailRoute
  '/payments/toss/success': typeof PaymentsTossSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/club'
    | '/games'
    | '/lessons'
    | '/me'
    | '/records'
    | '/club/attendance'
    | '/club/manage'
    | '/club/schedule'
    | '/club/'
    | '/payments/toss/fail'
    | '/payments/toss/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/games'
    | '/lessons'
    | '/me'
    | '/records'
    | '/club/attendance'
    | '/club/manage'
    | '/club/schedule'
    | '/club'
    | '/payments/toss/fail'
    | '/payments/toss/success'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/club'
    | '/games'
    | '/lessons'
    | '/me'
    | '/records'
    | '/club/attendance'
    | '/club/manage'
    | '/club/schedule'
    | '/club/'
    | '/payments/toss/fail'
    | '/payments/toss/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClubRoute: typeof ClubRouteWithChildren
  GamesRoute: typeof GamesRoute
  LessonsRoute: typeof LessonsRoute
  MeRoute: typeof MeRoute
  RecordsRoute: typeof RecordsRoute
  PaymentsTossFailRoute: typeof PaymentsTossFailRoute
  PaymentsTossSuccessRoute: typeof PaymentsTossSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/attendance': {
      id: '/club/attendance'
      path: '/attendance'
      fullPath: '/club/attendance'
      preLoaderRoute: typeof ClubAttendanceRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/manage': {
      id: '/club/manage'
      path: '/manage'
      fullPath: '/club/manage'
      preLoaderRoute: typeof ClubManageRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/schedule': {
      id: '/club/schedule'
      path: '/schedule'
      fullPath: '/club/schedule'
      preLoaderRoute: typeof ClubScheduleRouteImport
      parentRoute: typeof ClubRoute
    }
    '/payments/toss/fail': {
      id: '/payments/toss/fail'
      path: '/payments/toss/fail'
      fullPath: '/payments/toss/fail'
      preLoaderRoute: typeof PaymentsTossFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/toss/success': {
      id: '/payments/toss/success'
      path: '/payments/toss/success'
      fullPath: '/payments/toss/success'
      preLoaderRoute: typeof PaymentsTossSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClubRouteChildren {
  ClubAttendanceRoute: typeof ClubAttendanceRoute
  ClubManageRoute: typeof ClubManageRoute
  ClubScheduleRoute: typeof ClubScheduleRoute
  ClubIndexRoute: typeof ClubIndexRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubAttendanceRoute: ClubAttendanceRoute,
  ClubManageRoute: ClubManageRoute,
  ClubScheduleRoute: ClubScheduleRoute,
  ClubIndexRoute: ClubIndexRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClubRoute: ClubRouteWithChildren,
  GamesRoute: GamesRoute,
  LessonsRoute: LessonsRoute,
  MeRoute: MeRoute,
  RecordsRoute: RecordsRoute,
  PaymentsTossFailRoute: PaymentsTossFailRoute,
  PaymentsTossSuccessRoute: PaymentsTossSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
