/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClubRouteImport } from './routes/club'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as MeRouteImport } from './routes/me'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as ClubIndexRouteImport } from './routes/club.index'
import { Route as ClubAttendanceRouteImport } from './routes/club.attendance'
import { Route as ClubFinanceRouteImport } from './routes/club.finance'
import { Route as ClubManageRouteImport } from './routes/club.manage'
import { Route as ClubMembersRouteImport } from './routes/club.members'
import { Route as ClubMoreRouteImport } from './routes/club.more'
import { Route as ClubNoticesRouteImport } from './routes/club.notices'
import { Route as ClubRankingRouteImport } from './routes/club.ranking'
import { Route as ClubScheduleRouteImport } from './routes/club.schedule'
import { Route as ClubsClubIdRouteImport } from './routes/clubs.$clubId'
import { Route as ClubsFindRouteImport } from './routes/clubs.find'
import { Route as ClubsNewRouteImport } from './routes/clubs.new'
import { Route as ClubsClubIdIndexRouteImport } from './routes/clubs.$clubId.index'
import { Route as ClubsClubIdLessonsRouteImport } from './routes/clubs.$clubId.lessons'
import { Route as ClubsClubIdMembersRouteImport } from './routes/clubs.$clubId.members'
import { Route as ClubsClubIdScheduleRouteImport } from './routes/clubs.$clubId.schedule'
import { Route as PaymentsTossFailRouteImport } from './routes/payments.toss.fail'
import { Route as PaymentsTossSuccessRouteImport } from './routes/payments.toss.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubAttendanceRoute = ClubAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ClubRoute,
} as any)
const ClubFinanceRoute = ClubFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ClubRoute,
} as any)
const ClubManageRoute = ClubManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ClubRoute,
} as any)
const ClubMembersRoute = ClubMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ClubRoute,
} as any)
const ClubMoreRoute = ClubMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => ClubRoute,
} as any)
const ClubNoticesRoute = ClubNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => ClubRoute,
} as any)
const ClubRankingRoute = ClubRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => ClubRoute,
} as any)
const ClubScheduleRoute = ClubScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ClubRoute,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsFindRoute = ClubsFindRouteImport.update({
  id: '/clubs/find',
  path: '/clubs/find',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsNewRoute = ClubsNewRouteImport.update({
  id: '/clubs/new',
  path: '/clubs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsClubIdIndexRoute = ClubsClubIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubsClubIdRoute,
} as any)
const ClubsClubIdLessonsRoute = ClubsClubIdLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => ClubsClubIdRoute,
} as any)
const ClubsClubIdMembersRoute = ClubsClubIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ClubsClubIdRoute,
} as any)
const ClubsClubIdScheduleRoute = ClubsClubIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ClubsClubIdRoute,
} as any)
const PaymentsTossFailRoute = PaymentsTossFailRouteImport.update({
  id: '/payments/toss/fail',
  path: '/payments/toss/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsTossSuccessRoute = PaymentsTossSuccessRouteImport.update({
  id: '/payments/toss/success',
  path: '/payments/toss/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRouteWithChildren
  '/games': typeof GamesRoute
  '/lessons': typeof LessonsRoute
  '/me': typeof MeRoute
  '/records': typeof RecordsRoute
  '/tournaments': typeof TournamentsRoute
  '/club/attendance': typeof ClubAttendanceRoute
  '/club/finance': typeof ClubFinanceRoute
  '/club/manage': typeof ClubManageRoute
  '/club/members': typeof ClubMembersRoute
  '/club/more': typeof ClubMoreRoute
  '/club/notices': typeof ClubNoticesRoute
  '/club/ranking': typeof ClubRankingRoute
  '/club/schedule': typeof ClubScheduleRoute
  '/clubs/$clubId': typeof ClubsClubIdRouteWithChildren
  '/clubs/find': typeof ClubsFindRoute
  '/clubs/new': typeof ClubsNewRoute
  '/club/': typeof ClubIndexRoute
  '/clubs/$clubId/lessons': typeof ClubsClubIdLessonsRoute
  '/clubs/$clubId/members': typeof ClubsClubIdMembersRoute
  '/clubs/$clubId/schedule': typeof ClubsClubIdScheduleRoute
  '/payments/toss/fail': typeof PaymentsTossFailRoute
  '/payments/toss/success': typeof PaymentsTossSuccessRoute
  '/clubs/$clubId/': typeof ClubsClubIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/games': typeof GamesRoute
  '/lessons': typeof LessonsRoute
  '/me': typeof MeRoute
  '/records': typeof RecordsRoute
  '/tournaments': typeof TournamentsRoute
  '/club/attendance': typeof ClubAttendanceRoute
  '/club/finance': typeof ClubFinanceRoute
  '/club/manage': typeof ClubManageRoute
  '/club/members': typeof ClubMembersRoute
  '/club/more': typeof ClubMoreRoute
  '/club/notices': typeof ClubNoticesRoute
  '/club/ranking': typeof ClubRankingRoute
  '/club/schedule': typeof ClubScheduleRoute
  '/clubs/find': typeof ClubsFindRoute
  '/clubs/new': typeof ClubsNewRoute
  '/club': typeof ClubIndexRoute
  '/clubs/$clubId/lessons': typeof ClubsClubIdLessonsRoute
  '/clubs/$clubId/members': typeof ClubsClubIdMembersRoute
  '/clubs/$clubId/schedule': typeof ClubsClubIdScheduleRoute
  '/payments/toss/fail': typeof PaymentsTossFailRoute
  '/payments/toss/success': typeof PaymentsTossSuccessRoute
  '/clubs/$clubId': typeof ClubsClubIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRouteWithChildren
  '/games': typeof GamesRoute
  '/lessons': typeof LessonsRoute
  '/me': typeof MeRoute
  '/records': typeof RecordsRoute
  '/tournaments': typeof TournamentsRoute
  '/club/attendance': typeof ClubAttendanceRoute
  '/club/finance': typeof ClubFinanceRoute
  '/club/manage': typeof ClubManageRoute
  '/club/members': typeof ClubMembersRoute
  '/club/more': typeof ClubMoreRoute
  '/club/notices': typeof ClubNoticesRoute
  '/club/ranking': typeof ClubRankingRoute
  '/club/schedule': typeof ClubScheduleRoute
  '/clubs/$clubId': typeof ClubsClubIdRouteWithChildren
  '/clubs/find': typeof ClubsFindRoute
  '/clubs/new': typeof ClubsNewRoute
  '/club/': typeof ClubIndexRoute
  '/clubs/$clubId/lessons': typeof ClubsClubIdLessonsRoute
  '/clubs/$clubId/members': typeof ClubsClubIdMembersRoute
  '/clubs/$clubId/schedule': typeof ClubsClubIdScheduleRoute
  '/payments/toss/fail': typeof PaymentsTossFailRoute
  '/payments/toss/success': typeof PaymentsTossSuccessRoute
  '/clubs/$clubId/': typeof ClubsClubIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/club'
    | '/games'
    | '/lessons'
    | '/me'
    | '/records'
    | '/tournaments'
    | '/club/attendance'
    | '/club/finance'
    | '/club/manage'
    | '/club/members'
    | '/club/more'
    | '/club/notices'
    | '/club/ranking'
    | '/club/schedule'
    | '/clubs/$clubId'
    | '/clubs/find'
    | '/clubs/new'
    | '/club/'
    | '/clubs/$clubId/lessons'
    | '/clubs/$clubId/members'
    | '/clubs/$clubId/schedule'
    | '/payments/toss/fail'
    | '/payments/toss/success'
    | '/clubs/$clubId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/games'
    | '/lessons'
    | '/me'
    | '/records'
    | '/tournaments'
    | '/club/attendance'
    | '/club/finance'
    | '/club/manage'
    | '/club/members'
    | '/club/more'
    | '/club/notices'
    | '/club/ranking'
    | '/club/schedule'
    | '/clubs/find'
    | '/clubs/new'
    | '/club'
    | '/clubs/$clubId/lessons'
    | '/clubs/$clubId/members'
    | '/clubs/$clubId/schedule'
    | '/payments/toss/fail'
    | '/payments/toss/success'
    | '/clubs/$clubId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/club'
    | '/games'
    | '/lessons'
    | '/me'
    | '/records'
    | '/tournaments'
    | '/club/attendance'
    | '/club/finance'
    | '/club/manage'
    | '/club/members'
    | '/club/more'
    | '/club/notices'
    | '/club/ranking'
    | '/club/schedule'
    | '/clubs/$clubId'
    | '/clubs/find'
    | '/clubs/new'
    | '/club/'
    | '/clubs/$clubId/lessons'
    | '/clubs/$clubId/members'
    | '/clubs/$clubId/schedule'
    | '/payments/toss/fail'
    | '/payments/toss/success'
    | '/clubs/$clubId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClubRoute: typeof ClubRouteWithChildren
  GamesRoute: typeof GamesRoute
  LessonsRoute: typeof LessonsRoute
  MeRoute: typeof MeRoute
  RecordsRoute: typeof RecordsRoute
  TournamentsRoute: typeof TournamentsRoute
  ClubsClubIdRoute: typeof ClubsClubIdRouteWithChildren
  ClubsFindRoute: typeof ClubsFindRoute
  ClubsNewRoute: typeof ClubsNewRoute
  PaymentsTossFailRoute: typeof PaymentsTossFailRoute
  PaymentsTossSuccessRoute: typeof PaymentsTossSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/attendance': {
      id: '/club/attendance'
      path: '/attendance'
      fullPath: '/club/attendance'
      preLoaderRoute: typeof ClubAttendanceRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/finance': {
      id: '/club/finance'
      path: '/finance'
      fullPath: '/club/finance'
      preLoaderRoute: typeof ClubFinanceRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/manage': {
      id: '/club/manage'
      path: '/manage'
      fullPath: '/club/manage'
      preLoaderRoute: typeof ClubManageRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/members': {
      id: '/club/members'
      path: '/members'
      fullPath: '/club/members'
      preLoaderRoute: typeof ClubMembersRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/more': {
      id: '/club/more'
      path: '/more'
      fullPath: '/club/more'
      preLoaderRoute: typeof ClubMoreRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/notices': {
      id: '/club/notices'
      path: '/notices'
      fullPath: '/club/notices'
      preLoaderRoute: typeof ClubNoticesRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/ranking': {
      id: '/club/ranking'
      path: '/ranking'
      fullPath: '/club/ranking'
      preLoaderRoute: typeof ClubRankingRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/schedule': {
      id: '/club/schedule'
      path: '/schedule'
      fullPath: '/club/schedule'
      preLoaderRoute: typeof ClubScheduleRouteImport
      parentRoute: typeof ClubRoute
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/find': {
      id: '/clubs/find'
      path: '/clubs/find'
      fullPath: '/clubs/find'
      preLoaderRoute: typeof ClubsFindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/new': {
      id: '/clubs/new'
      path: '/clubs/new'
      fullPath: '/clubs/new'
      preLoaderRoute: typeof ClubsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId/': {
      id: '/clubs/$clubId/'
      path: '/'
      fullPath: '/clubs/$clubId/'
      preLoaderRoute: typeof ClubsClubIdIndexRouteImport
      parentRoute: typeof ClubsClubIdRoute
    }
    '/clubs/$clubId/lessons': {
      id: '/clubs/$clubId/lessons'
      path: '/lessons'
      fullPath: '/clubs/$clubId/lessons'
      preLoaderRoute: typeof ClubsClubIdLessonsRouteImport
      parentRoute: typeof ClubsClubIdRoute
    }
    '/clubs/$clubId/members': {
      id: '/clubs/$clubId/members'
      path: '/members'
      fullPath: '/clubs/$clubId/members'
      preLoaderRoute: typeof ClubsClubIdMembersRouteImport
      parentRoute: typeof ClubsClubIdRoute
    }
    '/clubs/$clubId/schedule': {
      id: '/clubs/$clubId/schedule'
      path: '/schedule'
      fullPath: '/clubs/$clubId/schedule'
      preLoaderRoute: typeof ClubsClubIdScheduleRouteImport
      parentRoute: typeof ClubsClubIdRoute
    }
    '/payments/toss/fail': {
      id: '/payments/toss/fail'
      path: '/payments/toss/fail'
      fullPath: '/payments/toss/fail'
      preLoaderRoute: typeof PaymentsTossFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/toss/success': {
      id: '/payments/toss/success'
      path: '/payments/toss/success'
      fullPath: '/payments/toss/success'
      preLoaderRoute: typeof PaymentsTossSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClubRouteChildren {
  ClubAttendanceRoute: typeof ClubAttendanceRoute
  ClubFinanceRoute: typeof ClubFinanceRoute
  ClubManageRoute: typeof ClubManageRoute
  ClubMembersRoute: typeof ClubMembersRoute
  ClubMoreRoute: typeof ClubMoreRoute
  ClubNoticesRoute: typeof ClubNoticesRoute
  ClubRankingRoute: typeof ClubRankingRoute
  ClubScheduleRoute: typeof ClubScheduleRoute
  ClubIndexRoute: typeof ClubIndexRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubAttendanceRoute: ClubAttendanceRoute,
  ClubFinanceRoute: ClubFinanceRoute,
  ClubManageRoute: ClubManageRoute,
  ClubMembersRoute: ClubMembersRoute,
  ClubMoreRoute: ClubMoreRoute,
  ClubNoticesRoute: ClubNoticesRoute,
  ClubRankingRoute: ClubRankingRoute,
  ClubScheduleRoute: ClubScheduleRoute,
  ClubIndexRoute: ClubIndexRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

interface ClubsClubIdRouteChildren {
  ClubsClubIdLessonsRoute: typeof ClubsClubIdLessonsRoute
  ClubsClubIdMembersRoute: typeof ClubsClubIdMembersRoute
  ClubsClubIdScheduleRoute: typeof ClubsClubIdScheduleRoute
  ClubsClubIdIndexRoute: typeof ClubsClubIdIndexRoute
}

const ClubsClubIdRouteChildren: ClubsClubIdRouteChildren = {
  ClubsClubIdLessonsRoute: ClubsClubIdLessonsRoute,
  ClubsClubIdMembersRoute: ClubsClubIdMembersRoute,
  ClubsClubIdScheduleRoute: ClubsClubIdScheduleRoute,
  ClubsClubIdIndexRoute: ClubsClubIdIndexRoute,
}

const ClubsClubIdRouteWithChildren = ClubsClubIdRoute._addFileChildren(
  ClubsClubIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClubRoute: ClubRouteWithChildren,
  GamesRoute: GamesRoute,
  LessonsRoute: LessonsRoute,
  MeRoute: MeRoute,
  RecordsRoute: RecordsRoute,
  TournamentsRoute: TournamentsRoute,
  ClubsClubIdRoute: ClubsClubIdRouteWithChildren,
  ClubsFindRoute: ClubsFindRoute,
  ClubsNewRoute: ClubsNewRoute,
  PaymentsTossFailRoute: PaymentsTossFailRoute,
  PaymentsTossSuccessRoute: PaymentsTossSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
